basePath: /
definitions:
  application.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  application.LoginResponse:
    properties:
      token:
        type: string
    type: object
  application.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  application.RegisterResponse:
    properties:
      email:
        type: string
      id:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Serviço de autenticação da plataforma Aurora Home.
  title: Auth Service API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Credenciais de login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/application.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/application.LoginResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login de usuário
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Dados de registro
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/application.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/application.RegisterResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "409":
          description: Conflict
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Registro de novo usuário
      tags:
      - auth
swagger: "2.0"
